apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uwhz4veay-python
  janus-idp.io/tekton: uwhz4veay-python
  backstage.io/kubernetes-id: uwhz4veay-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uwhz4veay-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
