apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uwhz4veay-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uwhz4veay-python 
  name: uwhz4veay-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uwhz4veay-python 
